### ISSUE TITLE
Maximum call stack size exceeded when using 13.0.2 in Stack

### ISSUE THREAD

**Issue by Markus-Ende** [co-IT/ngrx-ducks#71]
I get this error message when using version 13.0.2:
```
ERROR RangeError: Maximum call stack size exceeded
    at isImmutableDuck (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:72:25)
    at eval (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:302:53)
    at Array.some (<anonymous>)
    at hasImmutableDuck (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:302:34)
    at eval (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:304:13)
    at Array.some (<anonymous>)
    at hasImmutableDuck (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:302:34)
    at eval (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:304:13)
    at Array.some (<anonymous>)
    at hasImmutableDuck (ngrx-ducks-12-ebdhbi.stackblitz.io/turbo_modules/@ngrx-ducks/core@13.0.2/fesm2015/ngrx-ducks-core.mjs:302:34)
```

You can reproduce it in the counter demo Stackblitz (I just explicitely set the version to 13.0.2 to force node module reinstallation): https://stackblitz.com/edit/ngrx-ducks-12-ebdhbi?file=package.json

**Comment by GregOnNet** [comment]
Hi @Markus-Ende ,

its interesting. Currently, I cannot reproduce the failure locally.

**Comment by GregOnNet** [comment]
Good Morning @Markus-Ende,

I released a new version of NgRx Ducks which should have fixed the issue.
StackBlitz has been updated as well: https://stackblitz.com/edit/ngrx-ducks-12-9ztnzp?file=src/app/counter/store/counter/counter.effects.ts
